version: "3.6"

services:
  mqtt-server:
    image: ghcr.io/everest/everest-demo/mqtt-server:${TAG}
    build: mosquitto
    pull_policy: build
    logging:
      driver: none

  manager:
    image: ghcr.io/everest/everest-demo/manager:${TAG}
    build: manager
    pull_policy: build
    deploy:
      resources:
        limits:
          cpus: "${EVEREST_MANAGER_CPUS}"
          memory: "${EVEREST_MANAGER_MEMORY}"
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    entrypoint: "sh /ext/source/build/run-scripts/run-sil.sh"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  node-red:
    image: ghcr.io/everest/everest-demo/nodered:${TAG}
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-flow.json
    ports:
      - 1880:1880
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
