FROM eclipse-mosquitto:2.0.10

COPY mosquitto.conf /mosquitto/config/mosquitto.conf

COPY run-test.sh /mosquitto/config/run-test.sh

LABEL org.opencontainers.image.source=https://github.com/everest/everest-demo
